version: 1.2.0.{build}
branches:
  only:
  - develop
  - master
skip_tags: true
configuration: Release
platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

environment:
  COVERALLS_REPO_TOKEN:
    secure: uJvwK/1oZXprkJ46fkTLEPBCGmHO15dUd1NxeUJl8P1l/TeaOhvlRoyjvZkAfLUT

before_build:
- nuget restore

build:
  project: MegaApiClient.sln
  verbosity: minimal

after_build:
- nuget pack MegaApiClient.nuspec

test_script:
  - ps: packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -targetdir:MegaApiClient.Tests -target:nunit3-console.exe "-targetargs:""bin\$env:CONFIGURATION\MegaApiClient.Tests.dll"" --workers=1" -returntargetcode "-filter:+[*]CG.Web.MegaApiClient* -[MegaApiClient.Tests]*" -output:opencoverCoverage.xml
  - ps: |
      if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER)
      {
        packages\coveralls.net.0.6.0\tools\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID
      }

artifacts:
- path: MegaApiClient.*.nupkg
  name: MegaApiClient package

deploy: off
