version: 1.6.0.{build}
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

skip_branch_with_pr: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: uJvwK/1oZXprkJ46fkTLEPBCGmHO15dUd1NxeUJl8P1l/TeaOhvlRoyjvZkAfLUT
  MEGAAPICLIENT_PASSWORD:
    secure: eRPOeRV2gdaN2nXPWl+YDA==

build_script:
- ps: .\build.ps1

test: off

artifacts:
- path: '.\artifacts\**\*.nupkg'
  name: Nuget packages

deploy:
- provider: NuGet
  server: https://www.myget.org/F/megaapiclient/api/v2
  api_key:
    secure: Fh+ZkfvseLY9z8DWLEFf1AlaJZQgzXCkWlIhHc1t4HLNo+w9+urXd2EyBLCTKzDv
  # Deploy symbol package too
  skip_symbols: false
  symbol_server: https://www.myget.org/F/megaapiclient/symbols/api/v2/package
